services:
  backend:
    build:
      context: ./backend
      target: dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: development
      # Vite utilisera cette URL pour appeler l'API en dev
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html


